github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/ashemaletube-downloader",
  "https://serp.co/products/ashemaletube-downloader/reviews/",
  "https://extensions.serp.co/ashemaletube-downloader",
  "https://browserextensions.io/ashemaletube-downloader"
]
